### ISSUE TITLE
Eagle template

### ISSUE THREAD

**Issue by jywarren** [oshwa/certification-mark#1]
An Eagle template including a well-formatted version of the OSHW certification mark. Help us out by opening a pull request with the file!

**Comment by kennethlimcp** [comment]
@jywarren happy to help if there's the official artwork available 👍

**Comment by jywarren** [comment]
Oh great, yes please! Isn't there an svg in the repo? Thanks!

**Comment by jywarren** [comment]
Solved in #3!
