### ISSUE TITLE
Need SVG (and other) templates which include the optional ID part

### ISSUE THREAD

**Issue by mithro** [oshwa/certification-mark#12]
Currently none of the templates include the optional ID part as shown here -> http://www.oshwa.org/wp-content/uploads/2016/10/OSHWAcert.png

Can we get an SVG template that with the ID in it so we can just update the value?

**Comment by jywarren** [comment]
Hi, would you be able or willing to submit an updated SVG? 

![mark](http://www.oshwa.org/wp-content/uploads/2016/10/OSHWAcert.png)

I think that vs. the example shown in the now-announced id spec, we'd like to have a slightly smaller font size and more space between the numbers and the mark:

![image](https://cloud.githubusercontent.com/assets/24359/21658307/0c9c2f74-d294-11e6-8144-b5094045da4a.png)

I think we could specify "monospace" as the font, as not everyone will have Deja Vu Sans Mono.

Thanks!

**Comment by mithro** [comment]
I'm afraid this is outside my skill set. Probably something the OSHA should invest in getting done...

**Comment by jywarren** [comment]
I'll try to spend some time on it early next week -- thanks for the suggestions -- but if anyone else is able to make an attempt in the next few days, please do!

**Comment by Junes-PhD** [comment]
I added text fields to the Kicad footprints.  Let me know if the text size needs adjusting.

**Comment by jywarren** [comment]
Fantastic, thank you. Left a comment over there.

**Comment by jywarren** [comment]
Hi, how does this look? 

https://github.com/oshwa/certification-mark/pull/16/files

**Comment by jadonk** [comment]
This looks like what I'd like to use. Can we get this merged so we can use it officially?

**Comment by jywarren** [comment]
Hi, @jadonk -- are you able to post an SVG file as described above, that we could merge? Thanks!

**Comment by jadonk** [comment]
I just used what you had on you branch and replaced it with my number: https://github.com/jadonk/beaglebone-blue/blob/oshwa-logo/docs/oshwa_logo_beaglebone_blue.svg 
https://github.com/jadonk/beaglebone-blue/commit/47abe07104be05ad1727aa7d82c2421599085893
