### ISSUE TITLE
String Length

### ISSUE THREAD

**Issue by dakloifarwa** [oshwa/certification-mark#19]
Hi,

I received a certification UID for my project and tried to create a certification mark.
Unfortunately my UID seems to be too long for your Inkscape template:
This is my UID: DE000004
How can I create a UID with such a long UID?
Thank you, regards Andreas

**Comment by u-fire** [comment]
Hello,
I'm not an Inkscape expert by any means. But this is how to edit the number using the svg template from  #12. 

1. Open the file in Inkscape and select the number section
2. Right click and choose 'Text and Font...'
3. A dialog will open with three tabs, 'Font', 'Text', and 'Variants'
4. In 'Text', edit the text to what you want and click 'Apply'

You will then need to drag the resizing arrows to get the right size. If there is a better way, I don't know it. For simplicity's sake, I have attached two svgs with your serial number, one with all 6 digits, and the other with only 4. I haven't confirmed it yet, but I believe 6 digits will need to be a quite large logo 

[de0004.zip](https://github.com/oshwa/certification-mark/files/1272047/de0004.zip)


to legibly be put on a PCB.

**Comment by justind000** [comment]
Hello,
I'm not an Inkscape expert by any means. But this is how to edit the number using the svg template from #12.

    Open the file in Inkscape and select the number section
    Right click and choose 'Text and Font...'
    A dialog will open with three tabs, 'Font', 'Text', and 'Variants'
    In 'Text', edit the text to what you want and click 'Apply'

You will then need to drag the resizing arrows to get the right size. If there is a better way, I don't know it. For simplicity's sake, I have attached two svgs with your serial number, one with all 6 digits, and the other with only 4. I haven't confirmed it yet, but I believe 6 digits will need to be a quite large logo to legibly be put on a PCB.
[de0004.zip](https://github.com/oshwa/certification-mark/files/1272053/de0004.zip)

**Comment by dakloifarwa** [comment]
Thank you for your help! Michael from OSHWA asked me to submit this issue to you two weeks ago. IMHO I find the solution with the reduced string better than the one with a modified UID. Maybe one day the UIDs will extend the 4-digit range and then it's better to have plenty numbers available :-)
What do you mean? You may talk to Michael for a consistent solution, too!
Thank you for your effort!

Best regards
Andreas


-- 
dakloifarwa
Andreas Dietz
Blumenweg 3a
93083 Obertraubling
Am 02.09.2017 11:20:57 schrieb μniversal fire <notifications@github.com>:
Hello,
I'm not an Inkscape expert by any means. But this is how to edit the number using the svg template from #12 [https://github.com/oshwa/certification-mark/issues/12].
* Open the file in Inkscape and select the number section
* Right click and choose 'Text and Font...'
* A dialog will open with three tabs, 'Font', 'Text', and 'Variants'
* In 'Text', edit the text to what you want and click 'Apply'
You will then need to drag the resizing arrows to get the right size. If there is a better way, I don't know it. For simplicity's sake, I have attached two svgs with your serial number, one with all 6 digits, and the other with only 4. I haven't confirmed it yet, but I believe 6 digits will need to be a quite large logo
de0004.zip [https://github.com/oshwa/certification-mark/files/1272047/de0004.zip]
to legibly be put on a PCB.

**Comment by mwweinberg** [comment]
We have finally addressed this in the readme and in the FAQs on the certification site.  OSHWA has now clarified that users have the choice between using the entire UID (e.g. US000001) or to compress it by eliminating the initial zeros (e.g. US1).
