### ISSUE TITLE
contribution on UID generation

### ISSUE THREAD

**Issue by anupam19** [oshwa/certification-mark#2]
I want to contribute in UID generation for OSHW mark. Let me have pull request to be accepted.

**Comment by jywarren** [comment]
Hi, Anupam19 - thanks, the UID schema has not been decided on yet, and I'm
not yet sure what the timeline is on it. But suggestions are welcome --
probably not as a PR, however. Thanks!

**Comment by ToniCorinne** [comment]
As the UIDs are now being generated for the certifications, I believe you can close out this issue @jywarren

**Comment by jywarren** [comment]
Thanks!!

**Comment by jywarren** [comment]
If you could drop in a link that'd be great, sorry I'm on my phone.
