### ISSUE TITLE
Requesting OSHW certification logo in Altium format.

### ISSUE THREAD

**Issue by xjordanx** [oshwa/certification-mark#5]
Please provide a link to the Altium format in CircuitMaker for those who are using that. The link is here:
circuitmaker.com/Projects/Details/CircuitMaker-Official/OSHWA-Certification-Logo

**Comment by jywarren** [comment]
Oh great! Can you screenshot it so I can see the template you've created?
Also, would it be possible to open a pull request with the file included so
we could host the template in this repo?

Thanks!

**Comment by xjordanx** [comment]
[OSHWA_Cert.zip](https://github.com/oshwa/certification-mark/files/607208/OSHWA_Cert.zip)
![2016-11-22 10_22_17-altium designer 16 1 - c__users_ben jordan_documents_electronic designs_wip_co](https://cloud.githubusercontent.com/assets/4589115/20536375/9fe5b4f8-b09d-11e6-86d8-fb2555d4f405.png)

**Comment by jywarren** [comment]
Looks great, thank you!

**Comment by jywarren** [comment]
Great, closed in #15.
