### ISSUE TITLE
Actual UIDs are 8-characters, templates show 6-character UIDs

### ISSUE THREAD

**Issue by benmalouf** [oshwa/certification-mark#7]
The design files in the templates were set up for 6-character UIDs but the actual UIDs are 8-characters long. The question then is whether the font size should be reduced to fit the same horizontal space as the UID in the template, or if the font size should be maintained and the UID gets wider.  

See attached for an illustration of the question.

![oshwa_mark_issue](https://cloud.githubusercontent.com/assets/23321747/20073999/b62a11c2-a4eb-11e6-8eaf-ada2f60337c7.png)

Thanks!

**Comment by jywarren** [comment]
Yes I see the cert codes were finalized! And yes, that sounds like a good
solution. Thanks! I guess we should create issues for each of the places
that need to be updated.

**Comment by benmalouf** [comment]
I'm sorry, which solution, the reduced font size? I do think the smaller font looks better than the wider version, more in line with your original design. However, I wasn't sure about line weight for printing, silk screening, etching, etc.  

Let me know how I can help from here.

**Comment by jywarren** [comment]
I think the smaller version, just aesthetically. I think people will
probably vary depending on their final print size, but we could start with
this as an ideal example.
