### ISSUE TITLE
Oops - Maybe my understanding

### ISSUE THREAD

**Issue by ghost** [oshwa/certification-mark#8]
was incorrect.

We used what we could find on the site a couple of days ago to create this for our project...

![oshwacert](https://cloud.githubusercontent.com/assets/23366512/20153608/6828004a-a678-11e6-8d73-cc64679c7afa.png)

Hopefully this will be o.k., at least until we can recreate it to more correctly reflect the most recent Mark.

Have a great afternoon!  :)

**Comment by jywarren** [comment]
Thanks, that's great -- perhaps this is a sub-issue, or comment on #7? May I close it out? Thank you!

**Comment by ghost** [comment]
jywarren - i guess i'm rather unfamiliar with this type of forum.  i guess we really had a question:  is our rendering above alright to use or should we redo it?
Thanks for any light you might be able to shed on this matter.  We don't want to run afoul of the regulations...

**Comment by jywarren** [comment]
Sure - that looks good, although i think ideally consistent font for the
numbers would be best... but if you've had to make a last-minute change to
it, and it's printing very small, i think it's perfectly suitable!
